name: appdev
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  percent_indicator: ^4.2.2
  shared_preferences: ^2.2.0  # ✅ Moved to correct section

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/bcgr.jpg
    - assets/image/logo.png
    - assets/font/

  fonts:
    - family: SuperPeace
      fonts:
        - asset: assets/font/SuperPeace.ttf
          weight: 700
